sudo: false
cache:
  directories:
    - "node_modules"
language: node_js
node_js:
  - "node"

before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

jobs:
  include:
    - stage: validity
      name: "Linting source"
      script: npm run lint-source
    - stage: validity
      name: "Linting tests"
      script: npm run lint-tests
    - stage: validity
      name: "Unit tests"
      script: npm run test-coverage && npm run report-coverage
    - stage: compile
      script: npm run compile

script:
  - fossa init
  - fossa analyze

after_success:
  - cd src && fossa test

notifications:
  webhooks: "https://app.fossa.io/hooks/travisci"